### ISSUE TITLE
Flipper issues on WOF (was: Lamps above 400 on Wheel of Fortune)

### ISSUE THREAD

**Issue by francisdb** [vpinball/pinmame#196] opened 2024-01-18 08:54 UTC
First, is there a better place to ask these questions?

This table used to play without issues but `Controller.ChangedLamps` now seems to return lamps over 400 where the table code has only 400 entries in the arrays. Is this expected as it might break more tables?

```
2024-01-18 09:46:07.837 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 580 state 255'
2024-01-18 09:46:07.847 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 583 state 255'
2024-01-18 09:46:07.866 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 581 state 255'
2024-01-18 09:46:07.886 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 582 state 255'
2024-01-18 09:46:11.757 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 580 state 0'
2024-01-18 09:46:11.788 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 583 state 0'
2024-01-18 09:46:11.916 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 581 state 0'
2024-01-18 09:46:12.167 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 582 state 0'
2024-01-18 09:46:40.307 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 601 state 0'
2024-01-18 09:46:36.137 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 609 state 255'
2024-01-18 09:46:40.317 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 595 state 247'
2024-01-18 09:46:40.338 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 595 state 121'
2024-01-18 09:46:40.357 INFO  [28830] [DebuggerModule::Print@4232] Script.Print 'lamp 588 state 0'
```

PINMAME_SHA beec0c3cda92d3df1caeeb8af83ef14b05e1cf06

**Comment by vbousquet** [comment] 2024-01-19 08:53
This is intended and is only for WOF and WPT. It happens that these tables have LED matrices which seem to be PWMed so I added them as such.

**Comment by francisdb** [comment] 2024-01-19 09:21
Ok, I guess it's then up to the table writers to account for these new lamps.

**Comment by toxieainc** [comment] 2024-01-29 21:48
Sidenote: As mentioned above, a similar patch is needed for WPT.

**Comment by francisdb** [comment] 2024-02-06 08:24
@vbousquet I also have issues with the flippers on WOF, sometimes they don't react or are stuck in the up position. Looks like some events get lost. Does that ring a bell?

**Comment by toxieainc** [comment] 2024-02-06 16:46
Is this with 10.8.0 or 10.8.1?

**Comment by francisdb** [comment] 2024-02-06 17:49
For now I can only reproduce it on standalone branch or 10.8.1 standalone, works fine on windows. And only for this table which is strange.

**Comment by jsm174** [comment] 2024-02-06 18:06
Your windows pinmame is on the absolute latest?

**Comment by francisdb** [comment] 2024-02-06 18:52
Latest pre-release vpinmame downloaded yesterday.

**Comment by jsm174** [comment] 2024-02-06 19:45
I'm at a loss, as to why this only a standalone issue. libpinmame is not doing anything to the data. (it was previously to support RGBs with VPE, but all that was reverted). Its running through all the same code as the win32com. 

Maybe I missed a `core_request_pwm_output_update();`

Maybe a second set of eyes could compare:

https://github.com/vpinball/pinmame/blob/699fabce6fb0f96ea0d8d31fa44ae3b92f45cc08/src/libpinmame/libpinmame.cpp#L1008-L1189

to

https://github.com/vpinball/pinmame/blob/699fabce6fb0f96ea0d8d31fa44ae3b92f45cc08/src/win32com/Controller.cpp#L858-L1112

**Comment by francisdb** [comment] 2024-02-06 20:04
Can you reproduce the issue on mac? Haven't tried that yet.

**Comment by toxieainc** [comment] 2024-02-07 09:26
I think that we still have some issues/regressions here and there with 10.8.1, compared to 10.8.0, so maybe this is related??

**Comment by toxieainc** [comment] 2024-02-07 09:27
@vbousquet Any idea maybe??

**Comment by francisdb** [comment] 2024-02-07 10:20
Made some progress as to find the cause of the issue

Commenting out `Controller.ChangedLamps` in the `LampTimer_Timer` solves the flipper issue. (with of course lamps no longer working)

**Comment by francisdb** [comment] 2024-02-07 10:48
Should I move this over to a new issue?

**Comment by mazjohn** [comment] 2024-02-20 16:30
WOF - lamps do not work at all in latest builds.  Flippers erratic/get stuck - cannot isolate. Tested with 10.73 x86 filal and 10.8 rc1 with same results

**Comment by francisdb** [comment] 2024-02-20 17:25
That specific issue is fixed by changing the array declarations from capacity 400 to 610 in the script.

**Comment by toxieainc** [comment] 2024-02-24 05:43
Flipper issues could be fixed now, please test @francisdb

**Comment by toxieainc** [comment] 2024-02-24 06:07
Doesn't work for me yet, so far, so reopening. @vbousquet for vis

**Comment by toxieainc** [comment] 2024-02-24 07:57
I'm never 100% sure if Vince gets the PinMAME issue mails, so pinging him explicitly for stuff that is related to his changes.

**Comment by vbousquet** [comment] 2024-02-24 08:54
I keep an eye on Github only (I also have a look from time to time to discord / VPF but the feedback is usually too largely spread and not enough cleanly reported to be usable) but I miss things. There are just too much. So no problem.

Regarding the SAM emulation issues. I have just pushed a new PR for these bugs which improves flipper emulation (lower latency, hack designed around IJ4 emulation bug only). The original implementation also used some nasty hacks to keep things running so it is a bit difficult to identify what should be removed since some hacks were only needed due to the lack of PWM support, other are needed due to emulation issue (like IJ4).

For WOF, I was not able to reproduce the issue (on the latest with teh latest fix), so I would need some more hints to have a look.

**Comment by francisdb** [comment] 2024-02-24 09:39
> I'm never 100% sure if Vince gets the PinMAME issue mails, so pinging him explicitly for stuff that is related to his changes.

Got that part but I suppose that's some kind of abbreviation?

![Screenshot_20240224-103847](https://github.com/vpinball/pinmame/assets/161305/ae106181-3077-423e-9e53-e00e2c3edd69)

**Comment by toxieainc** [comment] 2024-02-24 09:46
Simpler.. _vis_ibility

**Comment by francisdb** [comment] 2024-02-24 19:37
Issue still there for me with latest pinmame on standalone linux 10.8.1 and 7b0aafb49b6dbe7127261e3ba3737afe76e88e8

**Comment by francisdb** [comment] 2024-02-26 06:26
@toxieainc why can't I reopen this issue?

**Comment by toxieainc** [comment] 2024-02-26 07:00
No clue, reopening

**Comment by vbousquet** [comment] 2024-03-09 08:07
This is the latest issue (beside improving filtering) following the PWM changes but I still can't reproduce it.
Reading from the above, I'm not sure:
- if it happens on regular Window's version of VPX or if it only on standalone,
- if it still there following the latest script changes inside VPX (and especially cleanups of SAM flipper code).

@francisdb could you confirm if the bug is still there for you ? If so, could you provide a link to the offending table (to check if it is maybe a table script bug) ?

**Comment by francisdb** [comment] 2024-03-09 08:41
> For now I can only reproduce it on standalone branch or 10.8.1 standalone, works fine on windows. And only for this table which is strange.

https://vpuniverse.com/files/file/5501-wheel-of-fortune-stern-2007/

With patched script from https://github.com/jsm174/vpx-standalone-scripts/tree/master/Wheel%20of%20Fortune%20(Stern%202007)%201.0 (increased array sizes)

Still have flippers not always reacting or being stuck in up position with latest 10.8.1 branch but happens less often than before.

Not calling `Controller.ChangedLamps` still fixes the issue or makes it much less likely to happen.

@jsm174 can you reproduce this one on mac/linux?

**Comment by toxieainc** [comment] 2024-03-12 22:44
@francisdb Can you please test again with the latest build?

**Comment by francisdb** [comment] 2024-03-13 07:26
Issue persists with b06d8d4d48f9e2e9f3638a3f469002cb64035f0a
Do we have anybody else who can reproduce this issue?

**Comment by embryodead** [comment] 2024-03-16 10:35
As previous user say lastest vpx 10.8 build on windows with the lastest vpinmame build from yesterday.
wpt, wof and also big buck hunter, no insert on playfield even with the fix in the script and flipper stuck on wof(flippers are fine in indy and wpt).

**Closed** 2024-03-17 08:50 UTC
Labels: regression

**Comment by francisdb** [comment] 2024-03-17 16:00
Confirming this is fixed. Thanks @vbousquet !
