### ISSUE TITLE
The Walking Dead LE slowdown on 64 bit / add AT91 JIT to non-x86-32bit path

### ISSUE THREAD

**Issue by RobbyKingPin81** [vpinball/pinmame#111] opened 2023-04-24 19:50 UTC
At the start of the game everything runs fine. But after a while the dmd shows massive slowdown. It is possible the crossbow has something to do with it. The ball will not launch, crossbow goes back to the base position and after a while the ball spits out from the pivotpoint of the crossbow. After that the game froze down so hard nothing seems to work right anymore and the game is virtually unplayable. On 32 bit version no issues at all.

**Comment by toxieainc** [comment] 2023-04-27 10:55
This is unfortunately for now the 'normal' behavior.
On 64bit, or non-x86 platforms in general, the AT91 JIT code path is non existant, so some machines relying on that emulation will be wacky or incaccurate.

**Comment by RobbyKingPin81** [comment] 2023-04-27 11:23
Thanks for the reply. I hope it's something fixable in the future because I want to release a mod in the future when this problem is solved. I can use the 32 bit because I mixed both versions in my install but I have seen many people that just went for the 64 bit versions of VPX and VPinMame and didn't look back to the 32 bit versions anymore. You guys knocked it out of the park with the 64 bit stuff, most games work perfect. Are there more Stern tables with simular issues that you know off? Asking this to help me select a new table to mod while I delay this for now

**Comment by mjrgh** [comment] 2023-04-28 04:26
If anyone wants to implement a stop-gap (pending someone getting motivated enough to do an i64 translation), I have a suggestion that might be relatively low effort.  Have the 64-bit PInMame kick off a child process running a 32-bit .exe that only runs the sound board emulator.  That would let the existing JIT code run, since that part would be in 32-bit space, while making everything transparent to the 64-bit host process (VP).  The two can communicate via a pipe (or any other IPC mechanism, but a pipe is probably easiest).  That would only require some mucking around with PinMame build configurations, and not much new code; the only really new thing would be the communication mechanism.

**Comment by toxieainc** [comment] 2023-04-30 07:23
The thing is that we're now also multi-OS/platform. So going forward, we should either make the non-JIT version behave the same as the JIT version (at cost of CPU cycles :/), or make the JIT code also work on 64bit and Arm.

**Comment by mjrgh** [comment] 2023-04-30 17:42
> The thing is that we're now also multi-OS/platform. So going forward, we should either make the non-JIT version behave the same as the JIT version (at cost of CPU cycles :/), or make the JIT code also work on 64bit and Arm.

Certainly, which is why I called it a stopgap.  If a comprehensive solution is in the works, a stopgap obviously isn't necessary.  I just got the impression from your earlier comment that it might be a while.  If that's the case, then at least Win64 doesn't necessarily have to wait as long as everyone else, since there's this potential way to extend the JIT functionality to this one additional platform, in the near term, with relatively little work (compared to building out the JIT for IA64, ARM, Linux, and MacOS).

**Comment by toxieainc** [comment] 2023-05-02 06:24
Is there some library (and i hope the answer is not LLVM ;)) that could help in making emitting code a bit less platform/OS dependent, maybe at least for x86/64?

**Comment by toxieainc** [comment] 2023-05-02 06:27
Maybe something like https://asmjit.com/ ? That includes even Arm, and seems to be used by quite some multi-platform larger projects (e.g. GZDoom).

**Comment by wiesshund** [comment] 2023-06-25 13:10
> Are there more Stern tables with simular issues that you know off? 

A lot of Stern and some newer williams, perhaps others
Results vary from just flat out crashing to things seeming ok at 1st and then the DMD becomes out of sync with the table

depends on the rom, and sometimes how long your game lasts

**Comment by iaakki** [comment] 2023-10-12 09:11
Getting that asmjit in would be wonderful. That would make it work also for the standalone version.

**Comment by djrobx** [comment] 2023-11-12 18:31
Another option is to update the interrupt handling code to be more accurate in the C++ emulation.

At the time I worked on this, it was prohibitively slow to check if IRQs need to be serviced at all the correct times in the interpreted version.    I'm possibly hazy on the details, but I think on every POP call you ought to check to see if IRQs need to be serviced.   The interpreter didn't do this, but when I implemented it in the JIT code it solved the stalling issues. 

Might also be worthwhile playing with the timing constants in the AT91 code.  You might find some that work better with different games.    ACDC and Metallica were actually the harder ones to get working correctly as they use a more "brute force" technique to write to the serial port. 

Option 3 is to just look at replacing the ARM emulator with a better one.   Better emulation would probably help SAM as well as future hardware we will undoubtedly want to support at some point.

**Comment by SlayerSlipknot** [comment] 2024-11-03 14:06
Any news on this topic?

I really would love to see The Walking Dead working on 64bit. 

Maybe something like DllSurrogate would help to make the code working with 64 bit. I'm a noob on this, but I remember that something like this was used to make other Vpin related software work with 64 bit.

**Comment by rashoultes** [comment] 2024-12-10 14:32
I noticed a recent nightly update SAM: better nodeboard emulation (TWD, Mustang, Star Trek, Metallica, … #1264.  Does this mean the DMD slowdown might be fixed?

**Comment by djrobx** [comment] 2024-12-10 18:40
I looked at the PR.    Very nice, but hard to say if it fixes this or not.  The PR does not seem to change the AT91 serial implementation (how it reads/writes to the serial port), where I believe the sticking problem comes from.   Originally, Walking Dead LE and Mustang relied on some fairly nasty hacks to get the lights going at startup, because I wasn't able to determine the hardware responses the ROM was looking for.   This PR addresses that.

It might incidentally work based on the emulation now sending correct responses from the node boards.   Or it might still suffer from IRQ timing problems.    Only way to know for sure is to try it.    Either way that PR is a big step in the right direction.

**Comment by vbousquet** [comment] 2024-12-10 19:28
I splitted the PR in 2 parts:
- the first part are AT91 serial fixes. These were causing issues with lights stopping in Metallica, or in TWD after a few games, since the AT91's USART would end up in an invalid state. This should be fixed now by the first commit of the PR
- the second is the nodeboard protocol implementation. In the end, I'm not sure this is really needed but it is more clean and allowed to really debug the USART (and also gives some documentation for later contributions).

I don't know if these were the only problem for TWD (and other SAM games) since there are also issues regarding SAM timing (see CSI and IJ4) but it should at least go in the right direction

**Comment by djrobx** [comment] 2024-12-10 21:34
If you fixed USART state problems that will likely take care of it.  

CSI and IJ4 literally drove me insane trying to figure out.    SAM used to have a lot of audible and visible timing problems, compared to my real Family Guy machine.   I fixed most of those by implementing interrupt controller priorities, however, when those are in place, IJ and CSI won't launch balls.   

Around the same time I fixed the IRQ implementation, someone else figured out you could slow the SAM CPU timing to get the launching to work.   But it seemed like with more correct IRQ handling, there were no timings that worked for IJ & CSI, so I just put the hack back into place and reverted the IRQ handling in those cases.

**Comment by toxieainc** [comment] 2024-12-10 21:54
At least it doesn't work now if one removes the existing timing hack. So there must still be more to it.

**Comment by iaakki** [comment] 2024-12-10 23:13
Flupper just confirmed that TWD works a lot better in 64bit. Still some stutter at EoB, but he says it is on bar with 32bit pinmame. This is great news!

**Comment by vbousquet** [comment] 2024-12-11 18:56
I will close since the user reports are that this seems now fixed

**Closed by vbousquet** 2024-12-11 18:56 UTC
Labels: bug, enhancement

**Comment by toxieainc** [comment] 2024-12-16 12:37
Will track the AT91 JIT as separate issue then
