### ISSUE TITLE
1238 crashes editor on every exit

### ISSUE THREAD

**Issue by Loadedweapon** [vpinball/pinmame#369] opened 2024-11-08 22:09 UTC
1238 crashes editor on every exit.. I know 1122 was good thats the last one I was on. have to test more

**Comment by Kraken74** [comment] 2024-11-09 11:08
I noticed the crashes starting at 1154 (1144 did not crash).

**Comment by vbousquet** [comment] 2024-11-10 08:16
Duplicate of https://github.com/vpinball/pinmame/issues/368

**Closed by vbousquet** 2024-11-10 08:16 UTC
