### ISSUE TITLE
Vpinmame X64 hangs if using altsound 2 and Pinsound is not running

### ISSUE THREAD

**Issue by alaw-lufc** [vpinball/pinmame#126] opened 2023-05-31 09:52 UTC
(same issue as https://github.com/vpinball/pinmame/issues/81)

VPinMAME-sc-3.6-450-9d295cf-win-x64 will hang on startup if altsound mode is set to 2 but Pinsound is not running.

When Pinsound Studio 18.8.3 is running vpinmame X64 altsound 2 can still work as seen in the log part of the Pinsound window below;
![image](https://github.com/vpinball/pinmame/assets/73988577/d3ac9e76-5209-4f0a-a4bb-cbab62af23e5)
![image](https://github.com/vpinball/pinmame/assets/73988577/ada69100-07de-4dfc-85e7-ef4b206b2a6e)

This behaviour will also cause VPX X64 to hang at "starting game scripts" if Pinsound is not running. Ideally the game would still launch as it does in 32bit and use rom sounds when Pinsound is not running.

(a copy of Pinsound 18.8.3 is available here if that helps [https://www.dropbox.com/s/n66z7ylpwzld1uw/PinSoundStudio-windows-18.8.3.zip?dl=0](url))

**Comment by toxieainc** [comment] 2023-06-04 09:14
@droscoe Could you maybe have a look why this hangs? As you're revisiting the other altsound path at the moment anyway.  :)

**Comment by droscoe** [comment] 2023-06-04 12:07
> (same issue as #81)
> 
> VPinMAME-sc-3.6-450-9d295cf-win-x64 will hang on startup if altsound mode is set to 2 but Pinsound is not running.
@alaw-lufc  Can you provide the steps you used to show this problem.  I did a quick test using your initial description and did not reproduce the issue.  Thanks!

**Comment by droscoe** [comment] 2023-06-04 15:17
UPDATE:
I was able to reproduce the issue.  I can't get a proper stack trace from VS.  Says all running threads are external processes.  Here's what I see:
```
PinSound: Cannot open slot: \\.\mailslot\PinSoundStudio. Error: 2.
PinSound: Communication read slot opened: \\.\mailslot\PinSoundPinMAME.
PinSound: WriteSlot failed with 2.
```
Seems it's stuck waiting on acknowledgement from PinSound, and doesn't time out.

**Comment by droscoe** [comment] 2023-06-04 15:30
I was able to reproduce the issue.  However, I couldn't get a proper stack trace.  VS complained that all running threads were external.  The log showed the following:
```
NMI RATE SET TO 248
set visible area 0-319 0-41
Physical width 322, height 202
cpunum_get_localtime() called for invalid cpu num!
using performance counter for timing ... cycles/second = 10000000
VGM logging mode: 00
width 640, height 400 depth 16
set visible area 0-0 0-0
vgm_open - Chip Type 03, Clock 3579545
Machine reset
PinSound: Cannot open slot: \\.\mailslot\PinSoundStudio. Error: 2.
PinSound: Communication read slot opened: \\.\mailslot\PinSoundPinMAME.
PinSound: WriteSlot failed with 2.
```
It looks like the code is waiting for a response from PinSound and not timing out

**Comment by droscoe** [comment] 2023-06-04 15:43
Confirmed.  The code is stuck waiting on a response to PinSound.   Only solution is to implement a timeout.
![test_pinmame](https://github.com/vpinball/pinmame/assets/10767925/892d3f00-0727-475a-bae4-e6ed9e6de69c)

**Comment by droscoe** [comment] 2023-06-04 16:15
By the way, this isn’t an issue when playing a table.  It just plays the original ROM sounds.  It only hangs in the test

**Comment by alaw-lufc** [comment] 2023-06-04 19:07
Thanks for looking it to quickly.

As you've reproduced the issue using the vpinmame test option i assume you don't need me to explain any steps. I'm a little surprised that VPX doesn't hang on startup for you though.

Using VPX 10.7.3.395 X64 if i open a table that uses a rom set to use altsound mode = 2 without Pinsound running it hangs here (and i have to end task it)
![image](https://github.com/vpinball/pinmame/assets/73988577/c688df91-7494-4d2a-84d9-195fa9f9b400)

If i open the same table with the same version of VPX, but the 32bit flavour the table does open and uses rom sounds when Pinsound is not running. 

From your comments i assume the 32bit route through the vpinmame code has a pinsound time out at present that the 64bit doesn't?, (or something like that anyway - sorry, i've no idea how the magic of vpinmame & pinsound talking to each other works!!)

**Comment by droscoe** [comment] 2023-06-05 10:21
@alaw-lufc hmmmm I might have done my table test on 32-bit.  I have a hard time understanding how the behavior could be different between 32/64-bit in this case.

**Comment by alaw-lufc** [comment] 2023-06-12 20:10
@droscoe No problem, my workaround will be to stick to 32bit VPX for now (as i have different systems set up to run with or without pinsound active to get rom or remixed sounds in game).  Will be great if it can be fixed at some stage though, thanks.

**Comment by droscoe** [comment] 2023-09-01 18:32
@alaw-lufc @toxieainc I have a fix for this issue.  It was a trivial change.  This bug is a bigger hassle than I originally thought.  Once you set the Alt Sound Mode to 2, if it then hangs, there is no way to set it back to something else for the table without running the VPinMAME setup in "test" mode.  My fix will catch the failure and allow the table to continue, albeit without the altsound

**Closed** 2023-09-03 08:18 UTC
Labels: bug

**Comment by alaw-lufc** [comment] 2023-09-04 07:18
@droscoe Thanks, gave it it quick test and everything looks to be working great with pinsound studio (running or not) with VPX x64.

` My fix will catch the failure and allow the table to continue, albeit without the altsound` - that's a handy little feature of VPM when altsound is set to 2 to allow you to switch between original & altsound mixes!

Thanks again
