### ISSUE TITLE
Hickup on AFM when destroying saucer in VPinmame after v.888

### ISSUE THREAD

**Issue by Regulations** [vpinball/pinmame#268] opened 2024-04-23 17:49 UTC
I have trouble with all the versions of VPinmame after "VPinMAME-sc-3.6-835-60613e8-win-x64.zip" with Attack From Mars G5K and afm_113 rom. Using latest VPX 10.8 GL. Everytime I destroy a ship, right when the explosion happens there is a small hickup in the DMD, both visual and sound. It also happens if I use ColorDMD. 

See video:
https://github.com/vpinball/pinmame/assets/31146448/c0e87685-4e73-4fa4-a961-0c76deeb4687

**Comment by toxieainc** [comment] 2024-04-23 20:55
@Regulations do you use an altsound package or rom/emulated sound?

**Comment by Regulations** [comment] 2024-04-24 06:27
> @Regulations do you use an altsound package or rom/emulated sound?

I'm using rom sound. 
Alt. Sound Mode=0
![afm_113b](https://github.com/vpinball/pinmame/assets/31146448/5b272e21-698e-44cb-a886-bdb2d8f082a3)

**Comment by Kraken74** [comment] 2024-04-24 15:50
Here to confirm this bug.  Tested with GL and regular (DX?) VPX 10.8.0 RC3 and RC2.  Problem disappears with vPinMame 3.6-822.  Just a slight pause/hickup during the final explosion of the UFO and the UFO solenoid does't fire the final time.  Tested on two different tables and it happens on both.

https://github.com/vpinball/pinmame/assets/5919849/d729d807-2209-40c6-93ce-7fb8f4f6d654

**Comment by Kraken74** [comment] 2024-04-24 15:58
I noticed it yesterday while testing my colorization and you can easily see AND hear the glitch here:
https://youtu.be/TSkgCbfZDZk?t=72

**Comment by eminence-afk** [comment] 2024-04-25 00:11
noticed this on medieval madness, too. upon destroying a castle. (109c)

also with demolition man when the game resets after match feature. (h6b)

**Comment by Loadedweapon** [comment] 2024-04-25 18:22
Just here to confirm this issue.. Just a slight pause on latest vpinmame

**Comment by sverrewl** [comment] 2024-04-26 13:06
> noticed this on medieval madness, too. upon destroying a castle. (109c)
> 
> also with demolition man when the game resets after match feature. (h6b)

Good to see we at least see the same. I asked in VPW Discord about some of the oddities but no-one tried to verify my findings. Haven't tried demo-man, but, I can't get the draw bridge to drop for MM.

**Comment by Loadedweapon** [comment] 2024-04-26 13:08
The draw bridge is a script issue and has been posted

**Comment by Loadedweapon** [comment] 2024-04-27 13:58
Great video of it lagging out. https://www.facebook.com/share/v/D42Mib4mVKmJckoo/?mibextid=oFDknk

**Comment by lminimart** [comment] 2024-04-27 15:51
Sorry this is upside down... but Bride of Pinbot is another clear example, especially in the post-game music, as seen here.

https://github.com/vpinball/pinmame/assets/128234486/4520e4ce-803f-4d95-ae10-7cf8727981d0

**Comment by lminimart** [comment] 2024-04-28 00:21
All of the tables that use this particular mpu seem affected, list attached
![image](https://github.com/vpinball/pinmame/assets/128234486/0dc56658-5ddd-45ee-ba91-d654655c6a7d)

**Comment by lminimart** [comment] 2024-04-28 00:27
All the tables that use these mpus seem affected (lists below)...

![image](https://github.com/vpinball/pinmame/assets/128234486/0a511761-10d4-464c-9419-324ad43a74fa)

![Screenshot_20240427-192236_Firefox](https://github.com/vpinball/pinmame/assets/128234486/fd4ab286-d533-4335-b0bf-7304c09570b4)

**Comment by vbousquet** [comment] 2024-04-28 19:51
@lminimart I think this bug is about the animation stutter as shown in the video of the first post on AFM. There is also a bug regarding sounds stutters in WPC here: https://github.com/vpinball/pinmame/issues/266#issuecomment-2081416325

Regarding the initial bug, I made some testing and I'm not able to reproduce in PinMame, while I always have it when using VPinMame. Note that the same goes for the sound WPC stutter bug.

**Comment by lminimart** [comment] 2024-04-28 21:44
Saw that other report, and the Scared Stiff comments there are indeed what I'm referring to. I suppose I conflated them, tho they seem related. Just glad it's being looked into!

**Comment by vbousquet** [comment] 2024-04-29 20:28
Some news on this: I took the time tpo look more in depth on the bug. It is clearly linked to the new PWM implementation as it is trigger since these tables use the legacy MODSOL which is now implemented using the new PWM path.

The issue seems to be a performance issue: on some situations the amount of update seems to rise fairly high (for AFM, all lights and flashers blinking when saucer is destroyed for example). The profiler shows as the biggest offender the eye flicker/fusion filter which is called a lot. The YM FM emulation is also quite heavy. I guess the sound stutters may have the same cause.

**Comment by lminimart** [comment] 2024-04-29 21:17
Curious: does this mean more powerful systems won't see the issue? Based on reports from others i know with pretty powerful systems, it sure seems to occur on those types of pcs, as well.

**Comment by vbousquet** [comment] 2024-04-29 21:51
@lminimart I made an experimental build with some improvments to this. If you can give it a try and see if it improves (solves ?) the bug for you, that would be nice. The build is here: https://github.com/vpinball/pinmame/actions/runs/8885882588

**Comment by lminimart** [comment] 2024-04-29 21:52
very happy to give it a go! i'll report back.

**Comment by vbousquet** [comment] 2024-04-29 22:12
Did it performs better with an old PinMame (the difference is now very slight) ?

**Comment by lminimart** [comment] 2024-04-29 22:16
Yes, the vpinmame I had installed before the latest beta never exhibited any of the audio stutter I'm hearing now on any of my systems. The two games I played of Bride of Pinbot with your test vpinmame were nearly without stutter, really only audible stutter in the post-game music, but audible every time in that part of the audio. I hope I'm answering the question correctly.

**Comment by Kraken74** [comment] 2024-04-30 14:51
> @lminimart I made an experimental build with some improvments to this. If you can give it a try and see if it improves (solves ?) the bug for you, that would be nice. The build is here: https://github.com/vpinball/pinmame/actions/runs/8885882588

Confirmed working fine with this version here.

**Comment by Loadedweapon** [comment] 2024-04-30 15:07
Much better!

**Comment by Smilelikejoker** [comment] 2024-04-30 20:34
Current VPinMAME 64bit SC rev 948.
Didn't notice the stutter on AFM this go around.  Much better!

**Comment by toxieainc** [comment] 2024-05-04 05:05
Closing then. Otherwise please complain again with what is still wrong with certain table(s). Thanks all!

**Closed by toxieainc** 2024-05-04 05:05 UTC

**Comment by toxieainc** [comment] 2024-05-11 19:52
I just commited some more tiny tweaks, maybe it improves a bit more even by that.
