### ISSUE TITLE
3.6 929 Breaks Medieval Madness

### ISSUE THREAD

**Issue by WaRcLaWz** [vpinball/pinmame#269] opened 2024-04-29 05:25 UTC
After upgrading to VPINMAME 3.6 929 the Medieval Madness table is now broken. The table will seem fine at first, but after destroying the castle once, the drawbridge will never drop again.

To reproduce, run the Medieval Madness Upgrade (Final) table from VPU using VPINMAME 3.6 929. Then destroy a castle, and attempt to drop the drawbridge again. You can hit the castle many times and it will not register a hit, and the castle will not drop.

The issue is a regression because it goes away if you revert back to 3.6 822

**Comment by francisdb** [comment] 2024-04-29 06:14
duplicate of #226

**Comment by GHOSTfaceKILLr1974** [comment] 2024-04-29 22:43
> duplicate of #226

From what I read in #266 I need to replace the entire MM script with the link provided. My question to you is what version of MM do I use as there are several out there.

**Comment by WaRcLaWz** [comment] 2024-04-29 23:02
I run the latest and best one from VPU that you can get here: https://vpuniverse.com/files/file/9784-medieval-madness-mod-nfozzy-fleep-sounds-lut-11/

**Closed** 2024-04-30 10:34 UTC
