### ISSUE TITLE
Medieval Madness castle lock broken

### ISSUE THREAD

**Issue by killerrabbit33** [vpinball/pinmame#339] opened 2024-10-06 04:43 UTC
3.6 929 seems to break the castle lock (not the drawbridge--that issue has been fixed with the replacement script). The castle lock (to the left of the drawbridge) appears to stop opening--the balls just bounce off of it--after the ball has gone through one of the side loops at least once.

**Comment by vbousquet** [comment] 2024-10-06 08:45
Duplicate of https://github.com/vpinball/pinmame/issues/269

**Closed by vbousquet** 2024-10-06 08:45 UTC
