### ISSUE TITLE
Latest 3-4 Vpinmame did Christmas tree from Bride of pinbot 

### ISSUE THREAD

**Issue by joco77** [vpinball/pinmame#248] opened 2024-03-11 18:23 UTC
Hi

Table url:

[https://vpuniverse.com/files/file/12029-the-machine-bride-of-pinbot-williams-1991-vpw-mod/](url)

![latest](https://github.com/vpinball/pinmame/assets/87610911/6fe7d1f4-6735-436a-b25f-a9a97eccf43f)
Vpinmame latest version (888) and with some from before it.

**Comment by vbousquet** [comment] 2024-03-11 21:52
@toxieainc I think this may be caused by this https://github.com/vpinball/pinmame/blob/963dfb17b27932c7e69e926f7aec8a630156f4f0/src/wpc/core.c#L2231

```
#ifndef LIBPINMAME // dimmed segments not wired at the moment?!
#ifdef VPINMAME
    if(g_fShowWinDMD || g_fShowPinDMD)
#endif
    // Enable PWM/dimmed segments for corresponding alphanum segment machines
    if(((core_gameData->gen & GEN_GTS3) && GTS3locals.alphagen) || (core_gameData->gen & (GEN_WPCALPHA_1 | GEN_WPCALPHA_2)))
      options.usemodsol |= CORE_MODOUT_ENABLE_PHYSOUT;
#endif
```

For VPinMame, you should not enable physics output unless requested by the client since it changes the range of the returned value from 0..1 to 0..255 likely causing the above bug

**Comment by jsm174** [comment] 2024-03-11 21:59
whatever fix you come up with, I'm guessing libpinmame should also be included now.

**Comment by toxieainc** [comment] 2024-03-11 23:07
@vbousquet True, good point.  :/
How could we make it happen then that just dimmed segments could be enabled for the internal and external display/DMD?
Cause then all users could automatically benefit on all existing tables (that was my intention).

**Comment by toxieainc** [comment] 2024-03-11 23:08
@jsm174 How/Where does libpinmame pick up the dimmed segments?

**Comment by jsm174** [comment] 2024-03-11 23:15
> @jsm174 How/Where does libpinmame pick up the dimmed segments?

Tbh I haven't researched any of that yet, but we are pretty close where all the `ifdef vpinmame` are done with `libpinmame`

**Comment by toxieainc** [comment] 2024-03-12 22:29
Fixed with latest commit

**Closed by toxieainc** 2024-03-12 22:29 UTC
Labels: bug, regression
